language: java

jdk:
  - openjdk11

install:
  - wget http://ftp.cuhk.edu.hk/pub/packages/apache.org//jmeter/binaries/apache-jmeter-5.1.1.tgz
  - tar -xzvf apache-jmeter-5.0.tgz

script:
  - ./runScripts.sh

branches:
  only:
    - master