language: java

env:
  - jmeter_version: 5.2.1

jdk:
  - openjdk11

install:
  - wget http://ftp.cuhk.edu.hk/pub/packages/apache.org//jmeter/binaries/apache-jmeter-${jmeter_version}.tgz
  - tar -xzvf apache-jmeter-${jmeter_version}.tgz

script:
  - ./runScripts.sh ${jmeter_version}

branches:
  only:
    - master
