language: java
cache:
  directories:
    - apache-jmeter-5.0

jdk:
  - openjdk11

install:
  - wget http://apache.01link.hk//jmeter/binaries/apache-jmeter-5.0.tgz
  - tar -xzvf apache-jmeter-5.0.tgz

script:
  - ./runScripts.sh

branches:
  only:
    - master