language: java

jdk:
  - openjdk11

install:
  - wget http://apache.01link.hk//jmeter/binaries/apache-jmeter-5.0.tgz
  - tar -xzvf apache-jmeter-5.0.tgz

script:
  - find ./src/ -name "*.jmx" > fileName.txt
  - cat fileName.txt
  - for file in $(<fileName.txt)
  - do
  - result=$(./apache-jmeter-5.0/bin/jmeter -n -t $file | grep 'Err:' | sed 's/.*(\([0-9]*\).*/\1/g')
  -   if [ $result -gt 0 ]
  -   then
  -     echo $file fail
  -     exit 1
  -   else
  -     echo $file succedd
  -   fi
  - done

branches:
  only:
    - master